### ISSUE TITLE
Request: AppImage or Flatpak

### ISSUE THREAD

**Issue by trymeouteh** [byoso/Nord-Manager#1]
Please make an AppImage or a Flatpak that can be easily downloaded and installed on any distro. I would personally prefer an AppImage for portability.

**Comment by probonopd** [comment]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter
- No repositories needed. Suitable/optimized for air-gapped (offline) machines
- Decentralized

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by byoso** [comment]
Now Nord Manager (since 2.0.0) can be installed on any distro with the geninstaller's installer. Geninstaller is a recent developpment, so, if you experience any issue with the provided installer, you'll be welcome to report the problem.

**Comment by dim6003** [comment]
Agree, standard .deb/.rpm packages would be welcomed too.
