### ISSUE TITLE
"appmenu-gtk-module" failed to load

### ISSUE THREAD

**Issue by Gladox114** [byoso/Nord-Manager#2]
Running Linux with Gnome and it failed to start the GUI but displays every 5-6 seconds a status with everything in the console. After searching a bit I realized that this isn't made for Gnome.

**Comment by byoso** [comment]
Interesting... could you tell me what os you use ?
In fact it is a PyGObject application (GTK), it is quite a standard but may not work if your os doens't load gtk, I suppose.

**Comment by byoso** [comment]
> Running Linux with Gnome and it failed to start the GUI but displays every 5-6 seconds a status with everything in the console. After searching a bit I realized that this isn't made for Gnome.

Interesting... could you tell me what os you use ?
In fact it is a PyGObject application (GTK), it is quite a standard but may not work if your os doens't load gtk, I suppose.
