### ISSUE TITLE
settings page too tall for screen, cannot maximize or resize

### ISSUE THREAD

**Issue by crisjolliff** [byoso/Nord-Manager#3]
The title says it all.
![Screenshot from 2020-07-10 16-31-14](https://user-images.githubusercontent.com/8423751/87200592-e0dd4000-c2ca-11ea-823a-6c9bbb41b19a.png)

**Comment by byoso** [comment]
Thank you for your comment, so I just made a new version to fix that, the setting page is now scrollable and a bit smaller, i hope it will fit well now.

**Comment by crisjolliff** [comment]
Fits perfectly now, with a little room to spare. Thanks for the prompt
attention!

Regards,

*Cris Jolliff*
765.562.2307
