### ISSUE TITLE
Ubuntu only?

### ISSUE THREAD

**Issue by jkw** [byoso/Nord-Manager#5]
Doesn't say in **readme.txt** that it is _Ubuntu only_.

Got this issue when running **install.sh**:
`   ~/H/Nord-Manager-master  ./install.sh                               ✔ 
[sudo] lösenord för jkw:

Försök igen.

[sudo] lösenord för jkw: 

sudo: apt: kommandot hittades inte`

**Comment by jeannemas** [comment]
It seems that it uses, in fact `apt`, which is the package manager for Debian based distros.

https://github.com/byoso/Nord-Manager/blob/5c57a317550b631058cd67a9e1072ff58a8268d7/install.sh#L5

**Comment by byoso** [comment]
Yes you are right... the install.sh should only work for debian based systems. I guess that could be easy to manually adapt the install.sh to your own system.
Anyway, I will mention it in the readme.

**Comment by byoso** [comment]
> It seems that it uses, in fact `apt`, which is the package manager for Debian based distros.
> 
> https://github.com/byoso/Nord-Manager/blob/5c57a317550b631058cd67a9e1072ff58a8268d7/install.sh#L5

**Comment by byoso** [comment]
> It seems that it uses, in fact `apt`, which is the package manager for Debian based distros.
> 
> https://github.com/byoso/Nord-Manager/blob/5c57a317550b631058cd67a9e1072ff58a8268d7/install.sh#L5

Yes you are right... the install.sh should only work for debian based systems. I guess that could be easy to manually adapt the install.sh to your own system.
Anyway, it is now mentioned in the readme.md
