### ISSUE TITLE
fresh install doesn't work

### ISSUE THREAD

**Issue by jpgeiger6789** [byoso/Nord-Manager#6]
wish I knew more about Ubuntu, don't know how to give much more information than this.

Downloaded a zipped copy of the code base.  Unzipped to the downloads directory.  Opened the install folder in terminal, ran sudo ./install.sh, got no error message.  Open NordManager, I get an error message the first time, and after that I get no error message, but it fails to run.

**Comment by byoso** [comment]
Hi, did you install and configure the official nordvpn CLI first ?
