### ISSUE TITLE
It installs, but won't run

### ISSUE THREAD

**Issue by somedeveloper00** [byoso/Nord-Manager#7]
![image](https://user-images.githubusercontent.com/79690923/178706674-3bd3514b-76f7-4413-889e-753fd1845c42.png)

**Comment by byoso** [comment]
Hi, could you be more specific ?
Anyway:
- Be sure you installed properly the official nordvpn CLI
- Enter your credentials in the official CLI
- only then you'll be able to use Nord Manager
- When the application is launched, it will not pop a window, you will have a new icon in your system tray as an interface.

**Comment by somedeveloper00** [comment]
hey. yes I'd logged in to the official nordvpn CLI and in fact I think it was RUNNING at the time of installing this repo. 
+ I didn't get any GUI or tray icon.

as a side note, I was running it on Ubuntu 20 
and as another side note, I can't give you any logged dump or other helpful traces as I have uninstalled the Ubuntu OS and switched back to Windows-only for now. I work on this laptop so I need my softwares at the ready, and being an Iranian, VPN is a must-have, which I couldn't properly have in Ubuntu, so...


since this seems like a my-end problem, feel free to close the issue. later I'll install Ubuntu 22 and try again and report back to you. 

thanks

**Comment by byoso** [comment]
Ok, so I close the issue, thank you anyway for your feed back, I apprectiate.
