### ISSUE TITLE
[solved] Doesn't detect "not logged in"

### ISSUE THREAD

**Issue by RobAnt** [byoso/Nord-Manager#8]
Was trying to tart a connection and it just didn't work with no feedback to the user.

From command line, "nordvpn status" returned:
Status: Disconnected
Trying to connect from command line "nordvpn c canada" returned:
You are not logged in.

If the "not logged in response occurs", ideally nord-manager should respond with "nordvpn login" which returns a URL to go to to authenticate.

**Comment by byoso** [comment]
Yes, you are right, it should be a good thing, less confusing. I'll probably do that the next time I work on nord manager.
Thank you for this feedback :)

**Comment by byoso** [comment]
Done ! :)
