### ISSUE TITLE
[solved]Install failed on Ubuntu 22.04.1 LTS

### ISSUE THREAD

**Issue by dim6003** [byoso/Nord-Manager#9]
Please find below result : 
````
**didier@T580:~/downloads/Nord-Manager$** ./installer 
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.16.0-unknown is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Defaulting to user installation because normal site-packages is not writeable
Collecting geninstaller
  Downloading geninstaller-1.2.2-py3-none-any.whl (27 kB)
Collecting silly-db>=2.0.1
  Downloading silly_db-2.0.2-py3-none-any.whl (13 kB)
Collecting flamewok>=1.1.0
  Downloading flamewok-1.1.0-py3-none-any.whl (11 kB)
Installing collected packages: flamewok, silly-db, geninstaller
  WARNING: The script flamewok is installed in '/home/didier/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script silly-db is installed in '/home/didier/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script geninstaller is installed in '/home/didier/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed flamewok-1.1.0 geninstaller-1.2.2 silly-db-2.0.2
Dependencies successfully installed.
Traceback (most recent call last):
  File "/home/didier/downloads/Nord-Manager/./installer", line 151, in <module>
    from flamewok.cli import cli
ModuleNotFoundError: No module named 'flamewok'
**didier@T580:~/downloads/Nord-Manager$**
````

**Comment by byoso** [comment]
First, thank you a lot for the report, it really helps ! :)

~/.local/bin is the default installation directory used by pip, it is supposed to be on PATH

For some reason, it is not on PATH on your system. So 2 possibilities :

- if ~/.local/bin is not in the PATH by default on Ubuntu 22.04 (it seems weird, it works flawlessly on Manjaro and Mint 21), so rebooting and running again the installer should definitely solve the problem (not only for nord manager, but for all apps that use a pip dependencie). If it is the first time that pip is used on your system, the PATH may not be incremented yet.

- your python version (I suppose it is 3.10) doesn't accept auto-imported dependence (unlikely), running the installer a second time will fix the problem.

Note for dev:
- the installer script should be improved to check if ~/.local/bin is in PATH, and if it is not, add it to the PATH without rebooting.
- the installer should try and send a massage to say "run me again" (ugly)

**Comment by dim6003** [comment]
I confirm pip was installed when installer asked for it, and python version is Python 3.10.6.
And for the PATH : 
```
didier@T580:~/Téléchargements$ declare -p PATH
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"

```

**Comment by byoso** [comment]
Ok, my PATH (linux mint 21) looks like this:
```
byoso@byoso-X411UN:~$ echo $PATH
/home/byoso/.local/bin:/home/byoso/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
~/.local/bin is in my PATH, and not in yours. I will do some tests with ubuntu 22.04 in a virtual machine to try to understand the problem.

Just to be sure: you do run Ubuntu within a classic user session, not directly as admin by default without connection to a user's account, or with some kind of exotic settings about users sessions, do you ?

**Comment by dim6003** [comment]
No, standard desktop install of Ubuntu, and 'didier' is my (standard) user declared during Ubuntu install.

**Comment by byoso** [comment]
OK, I get all the things done on Ubuntu, but there are a few things:

- first you will need one more dependence to install:
```
sudo apt install gir1.2-appindicator3-0.1
```
- after installing pip, don't forget to reboot (ubuntu wil then add the pip directory to its PATH)
- run the installer again

Everything should work fine this way. Please let me know.

Note for dev:
- Explain in the pip installation message that the PC needs to be rebooted
- replace appindicator with something that ubuntu have natively (deprecated ?).

**Comment by dim6003** [comment]
Installed gir1.2-appindicator3-0.1, then run installer again : 
```
didier@T580:~/Téléchargements/Nord-Manager$ ./installer 
Migration successfully applied: 00_initial_geninstaller.sql
geninstaller database initialized
Network;Utility;
geninstaller has successfuly installed 'Nord Manager' on your system
please read the geninstaller's help to know how to use it:
$ geninstaller -h
didier@T580:~/Téléchargements/Nord-Manager$ geninstaller list
================================================================================
                      Geninstaller: Installed Applications                      
===============================================================================|
NAME: 'Nord Manager'
COMMENTS: Unoficial NordVPN manager in the system tray (geninstaller)
TERMINAL ?: false
CATEGORIES: Network;Utility;
_______________________________________________________________________________|
didier@T580:~/Téléchargements/Nord-Manager$ 
```
However, no new icon in my system tray...
![image](https://user-images.githubusercontent.com/57224834/200033248-736af01e-0c8d-4760-abca-e172d6c38a30.png)

Edit : No new icon, even after reboot

**Comment by byoso** [comment]
Good !
Now all you have to do is to launch Nord Manager from your applications menu, as any other app, then you will see the icon in the system tray.
Please let me know if that works.

**Comment by dim6003** [comment]
Effectively, Thanks! One last question, how to make it to start automatically ?

**Comment by byoso** [comment]
In the Ubuntu's applications menu, you can find something called like "applications on start" (in french "applications au demarrage"), it will ask you a name, lets say 'Nord Manager', and a path to the app's main executable, here this path is :
```
~/.local/share/applications-files/Nord_Manager/app/nordmanager.py
```
I'm glad I could help, and thanks to your feedback, a few improvements are obviously comming soon.
